test windows
Signed-off-by: rashidakanchwala <rashida_kanchwala@mckinsey.com>

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -34,7 +34,8 @@ jobs:
         - name: Checkout code
           uses: actions/checkout@v4
 
-        - name: Clone latest kedro-starters release into package/starters
+        - name: Clone latest kedro-starters release (Linux)
+          if: runner.os != 'Windows'
           env:
             GH_E2E_AUTH_TOKEN: ${{ secrets.GH_E2E_AUTH_TOKEN }}
           run: |
@@ -52,9 +53,29 @@ jobs:
             fi
 
             mkdir -p package/starters
-            git clone --depth 1 --branch "$LATEST_TAG" \
-              https://github.com/kedro-org/kedro-starters.git package/starters
+            git clone --depth 1 --branch "$LATEST_TAG" https://github.com/kedro-org/kedro-starters.git package/starters
 
+        - name: Clone latest kedro-starters release (Windows)
+          if: runner.os == 'Windows'
+          env:
+            GH_E2E_AUTH_TOKEN: ${{ secrets.GH_E2E_AUTH_TOKEN }}
+          run: |
+            $headers = @{
+              "Accept" = "application/vnd.github+json"
+              "Authorization" = "Bearer $env:GH_E2E_AUTH_TOKEN"
+              "X-GitHub-Api-Version" = "2022-11-28"
+            }
+
+            $response = Invoke-RestMethod -Uri "https://api.github.com/repos/kedro-org/kedro-starters/releases/latest" -Headers $headers
+            $tag = $response.tag_name
+
+            if (-not $tag) {
+              Write-Error "Failed to get latest tag"
+              exit 1
+            }
+
+            mkdir package\starters
+            git clone --depth 1 --branch $tag https://github.com/kedro-org/kedro-starters.git package/starters
 
         - name: Setup Tests
           uses: "./.github/actions/setup_tests"
